Initial changes to prepare ifupdown2 for pushing into debian
Conflicts:
	ifupdown2/debian/control
	ifupdown2/debian/ifupdown2.examples
	ifupdown2/debian/ifupdown2.links
	ifupdown2/debian/ifupdown2.postinst
	ifupdown2/debian/ifupdown2.postrm
	ifupdown2/debian/rules
	ifupdown2/setup.py

diff --git a/ifupdown2/debian/ifupdown2.postrm b/ifupdown2/debian/ifupdown2.postrm
--- a/ifupdown2/debian/ifupdown2.postrm
+++ b/ifupdown2/debian/ifupdown2.postrm
@@ -1,12 +1,64 @@
-#!/bin/bash
+#!/bin/sh
+# postrm script for ifupdown2
+#
+# see: dh_installdeb(1)
 
 set -e
 
-udevlink=$(readlink /etc/udev/rules.d/80-networking.rules 2>/dev/null)
-[ -n "$udevlink" -a "$udevlink" == "/dev/null" ] && rm -f /etc/udev/rules.d/80-networking.rules
-udevlink=$(readlink /etc/udev/rules.d/60-bridge-network-interface.rules 2>/dev/null)
-[ -n "$udevlink" -a "$udevlink" == "/dev/null" ] && rm -f /etc/udev/rules.d/60-bridge-network-interface.rules
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-if [ "$1" = "purge" ] ; then
-    update-rc.d networking remove >/dev/null
-fi
+process_udev()
+{
+    udevlink=$(readlink /etc/udev/rules.d/80-networking.rules 2>/dev/null || true)
+    [ -n "$udevlink" -a "$udevlink" = "/dev/null" ] && rm -f /etc/udev/rules.d/80-networking.rules
+    udevlink=$(readlink /etc/udev/rules.d/60-bridge-network-interface.rules 2>/dev/null || true)
+    [ -n "$udevlink" -a "$udevlink" = "/dev/null" ] && rm -f /etc/udev/rules.d/60-bridge-network-interface.rules
+}
+
+postrm_remove()
+{
+    process_udev
+}
+
+# Note: We don't remove /etc/network/interfaces
+postrm_purge()
+{
+	rm -f /run/network/ifstatenew
+}
+
+case "$1" in
+	purge)
+		postrm_purge
+	;;
+
+	remove)
+		postrm_remove
+	;;
+
+
+	upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)
+	;;
+
+	*)
+		echo "postrm called with unknown argument \`$1'" >&2
+		exit 1
+	;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
